/****************************************************************
 * This file is part of the "2048cc GTK+2 Replayer".
 *
 * Copyright:    2014 (c) migf1 <mig_f1@hotmail.com>
 * License:      Free Software (see following comments for limitations)
 * Dependencies: misc.h, gamedata.h, gui.h
 * --------------------------------------------------------------
 *
 * Description
 * -----------
 *
 * A GTK+2 Replayer for replay-files generated by the 2048cc v0.3a3 game,
 * written in ISO C99 and the GTK 2.24.10 API. Source-wise it is meant to
 * be cross-platform across at least Windows and Linux. Providing a recent
 * version of GTK+2 is properly installed, the sources can be compiled 
 * with any ISO C99 aware compiler (such as gcc/mingw-gcc).
 *
 * License
 * -------
 *
 * This software is open-source, free software with only 3 limitations:
 *
 * 1. Keep it free and open-source.
 * 2. Do not attempt to make any kind of profit from it or from
 *    any derivatives of it.
 * 3. Always re-distribute the original package, along with any
 *    software you distribute based on this game.
 *
 * Disclaimer
 * ----------
 *
 * Use the program at your own risk! I take no responsibility for
 * any damage it may cause to your system.
 ****************************************************************
 */

//#include <glib/gi18n.h>

#include <stdlib.h>
#include <stdbool.h>

#include "misc.h"
#include "gamedata.h"
#include "gui.h"

#define MAXSIZ_FNAME              (255+1)

/* -------------------------------
 * Global Variables
 * -------------------------------
 */

bool global_debugOn;        /* too lazy to wrap it */

/* ---------------------------------------------------
 * Application entry point.
 * ---------------------------------------------------
 */
int main( int argc, char **argv )
{
	Gamedata *gamedata; /* core-data of the program */
	Gui  *gui = NULL;   /* my (barely) abstracted GUI */

	global_debugOn = true;

	/* gamedata to be passed to the gui */
	gamedata = make_gamedata();
	if ( NULL == gamedata ) {
		DBG_STDERR_MSG( "*** (fatal error) gamedata not inited!" );
		goto cleanup_and_exit_failure;
	}

	/* spawn the GTK+2 gui */
	gui = new_gui( &argc, &argv, gamedata );
	if ( NULL == gui ) {
		DBG_STDERR_MSG( "(fatal error) gui not inited!" );
		goto cleanup_and_exit_failure;
	}

	/* print debugging info about the locale */
	dbg_gui_locale_print_inherited(
		gui_get_locale( gui ),
		"Caller Locale Environment was:"
		);
	dbg_gui_locale_print_current(
		gui_get_locale( gui ),
		"GUI Locale Environment set to:"
		);

	gui_start( gui );

	/* cleanup & exit */
	gui_free( gui );
	gamedata_free( gamedata );
	exit( EXIT_SUCCESS );

cleanup_and_exit_failure:

	/* cleanup & exit due to fatal error */
	gui_free( gui );
	gamedata_free( gamedata );
	exit( EXIT_FAILURE );
}
